export enum FormFieldType {
  Rsi5 = 'rsi5',
  Rsi10 = 'rsi10',
  Rsv = 'rsv',
  K = 'k',
  D = 'd',
  K_D = 'k-d',
  BollMa = 'bollMa',
  BollUb = 'bollUb',
  BollLb = 'bollLb',
  Ma5 = 'ma5',
  Ma10 = 'ma10',
  Ma20 = 'ma20',
  Ma60 = 'ma60',
  Ma120 = 'ma120',
  Ma240 = 'ma240',
  Ema5 = 'ema5',
  Ema10 = 'ema10',
  Ema20 = 'ema20',
  Ema12 = 'ema12',
  Ema26 = 'ema26',
  Macd = 'macd',
  Osc = 'osc',
  Dif = 'dif',
  Obv = 'obv',
  Obv5Ma = 'obv5Ma',
  Obv10Ma = 'obv10Ma',
  Williams8 = 'williams8',
  Williams18 = 'williams18',
  T = 't',
  C = 'c',
  H = 'h',
  L = 'l',
  O = 'o',
  V = 'v',
}

export enum FormOperatorFieldType {
    Greater = '>',
    Less = '<',
    Equal = '==',
    GreaterEqual = '>=',
    LessEqual = '<=',
}


export enum FormRollbackFieldType {
  Today = "0",
  PreviousDay = "1",
  PreviousTwoDay = "2",
  PreviousThreeDay = "3",
  PreviousFourDay = "4",
  PreviousFiveDay = "5",
}